pessoas = list()
pessoa = list()
nota = list()
for x in range(0,2):
    pessoa.append(str(input('Digite seu nome:')).strip())
    nota.append(int(input('Digite Nota 1:')))
    nota.append(int(input('Digite Nota 2:')))
    pessoa.append(nota[:])
    pessoas.append(pessoa[:])
    nota.clear()
    pessoa.clear()
print(pessoas)
print(pessoas[0])
print(pessoas[0][1])
print(pessoas[0][1][1])